spring:
  application:
    name: deep-sqs
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deep-sqs
    username: postgres
    password: 123456
    hikari:
      pool-name: pocSqsPool
      maximumPoolSize: 2
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show_sql: false
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false

server:
  servlet:
    context-path: /deep-sqs

cloud:
  aws:
    stack:
      auto: false
    region:
      static: us-east-1
    sqs:
      queue-fifo: deep-sqs.fifo
      queue-fifo-dlq: deep-sqs-dlq.fifo
      queue-standard: deep-sqs-queue
      queue-standard-dlq: deep-sqs-queue-dlq

localstack:
  url:
    sqs: http://localhost:4576